require_relative './modules/variables'
require_relative './modules/scoring'
require_relative 'game'
require_relative 'shuffle'
require_relative 'player'
require_relative 'dialer'
require_relative 'interface'
